---
name: CI
on:
  push:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.0.1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.1.1
    - name: Install packages
      run: |
        apt-get install -y --no-install-recommends git-build-recipe pbuilder
    - name: Build package
      id: build-package
      run: |
        git-build-recipe --allow-fallback-to-native deluge.recipe deb
        pbuilder create --distribution bionic
        pbuilder build deb/deluge*.dsc

        echo "::set-output name=version::$(basename deb/deluge*.dsc .dsc | cut -d_ -f2)"
    - name: Login to DockerHub
      if: github.event_name != 'push' || github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/login-action@v1.10.0
      with:
        username: kvadevack
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2.3.0
      with:
        push: ${{ github.event_name != 'push' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: kvadevack/deluge:${{ steps.build-package.outputs.version }}
